### PR TITLE
NewMVC and API tests

### PR DESCRIPTION
**Pull request by javigomez**
This pull request closes #22 

It contains the same code plus several fixes in the tests to make it work in travis.

Please do not merge. This is still work in progress. I'm pulling it to see TravisCI response

### CODE REVIEW

**Comment by fastslack** [comment]
Thanks Javi! Testing instructions are the same of last PR?

**Comment by javigomez** [comment]
yes, but still haven't finished. There is some error in Travis that I haven't yet identified. I need to continue updating the current pull.

Do you have code updates to send to your branch too? if you need to do updates, do it in your pull #22. No issue, I will do the merges in my local. I will close the current pull #25  and pull it against your pull request #22  as we did last week.

**Comment by javigomez** [comment]
actually I'm going to close the current one meanwhile I send the new updates to avoid confusion.

**Comment by javigomez** [comment]
thanks :smile:

**Pull request merged**
